config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/welcome' => 'formularios#home'
  get 'formularios' => 'formularios#index' 
  post 'formularios' => 'formularios#import', as: :import_formularios
  get 'formularios/income' => 'formularios#income', as: :income_formularios
  #resources :formularios do
  #  collection { post :import }
  #end
 
end

app/controllers/formularios_controller.rb
class FormulariosController < ApplicationController

	def home
	end

	def index
		@formulario = Formulario.all
	end

	def import
		Formulario.import(params[:file])
		redirect_to formularios_path, notice: "Arquivo importado"
	end

	def income
		@total_price = 0.0
		@formulario = Formulario.all
		@formulario.each do |f|
			@price = f.item_price
			@count = f.purchase_count
			@total_price = @total_price + (@price * @count)
		end
		render 'income'
	end
end

app/views/formularios/income.html.erb
<div class="main">
  <div class="container">

	    	<!--div class="message"--> 

			  <p><b>Receita bruta total do arquivo </b></p>
			  <p><%= @total_price %> R$</p>
			  <hr>
			<!--/div-->
	    
    	<%= button_to "Voltar", formularios_path, method: :get %>

  </div>
</div>

app/views/formularios/index.html.erb
<div class="main">
  <div class="container">

  		<h3>Upload de arquivo</h3>
  		
  		<%= form_tag import_formularios_path, multipart: true do %>

  		<%= file_field_tag :file %>
  		<%= submit_tag "Import" %>

  		<% end %>

  		<br>
		<h3>Listando todos os dados do arquivo</h3>
    	<br>
    	
    	<% if @formulario.blank? %>
		    <p>Base de dados não preenchida...</p>
		<% else %>

			<%= button_to "Exibir receita bruta", income_formularios_path, method: :get %>
			<br>
			<hr>
		    <%= @formulario.each do |f| %>

	    	<!--div class="message"--> 
			  <p class="content"><b>Cliente: </b> <%= f.purchaser_name %></p> 
			  <p class="content"><b>Descrição do item: </b> <%= f.item_description %></p>
			  <p class="content"><b>Valor do item: </b> <%= f.item_price %></p> 
			  <p class="content"><b>Quantidade do item: </b> <%= f.purchase_count %></p> 
			  <p class="content"><b>Endereço do vendedor: </b> <%= f.merchant_address %></p> 
			  <p class="content"><b>Nome do vendedor: </b> <%= f.merchant_name %></p> 
			 
			   <hr/>
			<!--/div-->
	    	<% end %>
		<% end %>

    	<%= button_to "Voltar", welcome_path, method: :get %>

  </div>
</div>